import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//layout is the blueprint for all our pages, so whatever we nest in here will appear in all pages
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// @/ --> ./src/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {/* children is the placeholder for all the pages content */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
