//fonts are set up in the layout.js file
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

//config the font using the properties (check the index list)
const roboto = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* add your font configs to the body className */}
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
